files: ^app/|^alembic/versions/|^tests/
default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        name: Ruff linter
        args: [ "--fix" ]
      - id: ruff-format
        name: Ruff formatter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        exclude: ^alembic/|^tests/
        additional_dependencies: [
          pydantic==2.11.5,
          SQLAlchemy==2.0.41,
          types-redis==4.6.0.20241004,
        ]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks
