"""Init and add tables

Revision ID: 747ed4b8e121
Revises:
Create Date: 2025-05-28 18:00:16.042158

"""

import sqlalchemy as sa
from db import base_class
from alembic import op

# revision identifiers, used by Alembic.
revision = "747ed4b8e121"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("updated_at", base_class.DateTimeUTC(), nullable=True),
        sa.Column("created_at", base_class.DateTimeUTC(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat")),
        schema="app",
    )
    op.create_table(
        "message",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user", "assistant", name="messagerole", native_enum=False, length=50
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", base_class.DateTimeUTC(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["app.chat.id"],
            name=op.f("fk_message-chat_id-chat"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message")),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message", schema="app")
    op.drop_table("chat", schema="app")
    # ### end Alembic commands ###
